# Generated by Django 6.0 on 2026-05-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the Publisher.", max_length=50
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="The Publisher's website."),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="The Publisher's email address.",
                        max_length=254,
                    ),
                ),
            ],
        ),
    ]
