# Generated by Django 6.0 on 2026-05-11 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("form_example", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PublisherForm",
            new_name="Publisher",
        ),
    ]
