# Generated by Django 6.0 on 2026-05-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_register", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employee_register.position",
            ),
        ),
    ]
